###################################################################################
# Thank you Cameron Kerr for https://github.com/cameronkerrnz/logstash-plugin-dev #
###################################################################################
version: 2.1

jobs:
  build:
    parameters:
      logstash-version:
        type: string
    docker:
      - image: cameronkerrnz/logstash-plugin-dev:<< parameters.logstash-version >>
    steps:
      - checkout
      - restore_cache:
          keys:
            # https://discuss.circleci.com/t/checksum-different-before-and-after-bundle-install/17334/14
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run:
          name: Ruby Bundle Install
          command: bundle install
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Ruby Build Gem
          command: gem build logstash-output-mongodb.gemspec
      - run:
          name: Ruby Test with Rspec
          command: bundle exec rspec
      - persist_to_workspace:
          root: ./
          paths:
            - logstash-output-mongodb-*.gem
            - VERSION

  publish-github-release:
    docker:
      - image: circleci/golang:1.15.3
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get -u github.com/tcnksm/ghr
            ls --format=single-column ./artifacts
            repo_version=$(cat ./artifacts/VERSION)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} \
                -r ${CIRCLE_PROJECT_REPONAME} \
                -c ${CIRCLE_SHA1} \
                -delete \
                v${repo_version} ./artifacts/logstash-output-mongodb-${repo_version}.gem

workflows:
  version: 2
  build-test-publish-on-tag:
    jobs:
      - build:
          name: build-v<< matrix.logstash-version >>
          matrix:
            parameters:
              logstash-version: ["7.9"]
          filters:
            tags:
              only: /^v.*/
      - publish-github-release:
          requires:
            - build
          filters:
            # only act on version tags
            tags:
              only: /^v.*/
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
